"""add assistant sessions messages proposals turn logs

Revision ID: 186280b241a6
Revises: f9c3a1d2e4b5
Create Date: 2026-09-27 18:21:33.364648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186280b241a6'
down_revision: Union[str, Sequence[str], None] = 'f9c3a1d2e4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seen_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('assistant_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assistant_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_messages_session_id'), ['session_id'], unique=False)

    op.create_table('assistant_turn_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('reasoning_effort', sa.String(length=16), nullable=False),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assistant_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_turn_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_turn_logs_session_id'), ['session_id'], unique=False)

    op.create_table('pending_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('proposals', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assistant_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('pending_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_proposals_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_proposals_session_id'))

    op.drop_table('pending_proposals')
    with op.batch_alter_table('assistant_turn_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_turn_logs_session_id'))

    op.drop_table('assistant_turn_logs')
    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_messages_session_id'))

    op.drop_table('assistant_messages')
    with op.batch_alter_table('assistant_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_sessions_user_id'))

    op.drop_table('assistant_sessions')
    # ### end Alembic commands ###
