"""add child_kind to events

Revision ID: 79c5af78af77
Revises: 5c45adbe5657
Create Date: 2026-09-16 22:22:13.080310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c5af78af77'
down_revision: Union[str, Sequence[str], None] = '5c45adbe5657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_kind', sa.Enum('TRAVEL', 'CUSTOM', name='child_event_kind', native_enum=False), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('child_kind')

    # ### end Alembic commands ###
