"""add engagement compliance persona sleep and points models

Revision ID: 9af9a5e0d514
Revises: 79c5af78af77
Create Date: 2026-09-16 22:33:55.666171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af9a5e0d514'
down_revision: Union[str, Sequence[str], None] = '79c5af78af77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('persona_id', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.JSON(), nullable=False),
    sa.Column('tone_description', sa.JSON(), nullable=False),
    sa.Column('sample_lines', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('persona_id')
    )
    op.create_table('daily_actual_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('actual_events', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.String(length=50), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.persona_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('base_points', sa.Float(), nullable=False),
    sa.Column('streak_multiplier', sa.Float(), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('actual_bedtime', sa.DateTime(), nullable=False),
    sa.Column('actual_wake_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('EVENT', 'GLOBAL', name='engagement_scope', native_enum=False), nullable=False),
    sa.Column('ref_event_id', sa.Integer(), nullable=True),
    sa.Column('last_response_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_stage', sa.Enum('NORMAL', 'WEEK_1_TELEGRAM', 'WEEK_2_MUTED', 'WEEK_3_FINAL', name='escalation_stage', native_enum=False), nullable=False),
    sa.Column('stage_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ref_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_instance_id', sa.Integer(), nullable=False),
    sa.Column('reason_category', sa.Enum('OVERSLEPT', 'FATIGUE', 'PRIORITY_SHIFT', 'SCHEDULE_CONFLICT', 'FORGOT', 'TRANSIT_ISSUE', 'OTHER', name='non_compliance_category', native_enum=False), nullable=False),
    sa.Column('reason_text', sa.String(length=150), nullable=True),
    sa.Column('llm_triggered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_instance_id'], ['event_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_users_selected_persona_id_personas', 'personas', ['selected_persona_id'], ['persona_id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_selected_persona_id_personas', type_='foreignkey')

    op.drop_table('compliance_reports')
    op.drop_table('engagement_states')
    op.drop_table('sleep_logs')
    op.drop_table('points_ledger')
    op.drop_table('persona_conversations')
    op.drop_table('daily_actual_logs')
    op.drop_table('personas')
    # ### end Alembic commands ###
